### ISSUE TITLE
l10n: Singular and plural

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/nextcloud-upload#23]
@skjnldsv Thanks for your input for adding text strings to the translations 👍.
Change the following text strings to be singular and plural:
```
{estimate} seconds left
{hours} hours and {minutes} minutes left
{minutes} minutes left
```
Also note that in some languages there is also a different variation for the number 2 😉.

Should the following text strings not start with a capital letter?

```
a few seconds left
estimating time left
paused
```

**Comment by skjnldsv** [comment]
Hey, this is still a WIP
Also see the discussion https://github.com/nextcloud/nextcloud-upload/issues/17 :)

**Comment by Valdnet** [comment]
Thank you for the information. I close 😉.
