### ISSUE TITLE
Is this a new project (!?) at Transifex?

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/nextcloud-upload#29]
Hello @skjnldsv ,

some hours ago a new project has been added to Transifex.
By intention?
The project has one resource called "messages.pot" and no description on any field.

Is this repository an app? If so, it should be a resource and not a project on Transifex.

I couldn't message you on cloud.nextcloud.com, so this way.

Please send me feedback.

**Comment by rakekniven** [comment]
I locked the resource at Transifex to prevent translators starting their work before this issue is solved.

Notes:
- This repo is missing .tx config file
- No change at docker-ci. What kind of magic is it?

**Comment by Valdnet** [comment]
> What kind of magic is it?

:scream:

Probably @skjnldsv knows how to do it 😁.

**Comment by skjnldsv** [comment]
> By intention?

Yes, but you can keep it locked, translations might change in a near future, see #17

**Comment by Valdnet** [comment]
> Yes, but you can keep it locked, translations might change in a near future, see #17

 In my opinion, I would not block translations. It's good to know how they develop and you can always add some suggestions and corrections. So far, there are not so many text strings.
